apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-emailservice-config-map
  labels:
    env: staging
    businessUnit: emailservice
data:
  CLOUDAMQP_URL: amqps://ixoayxee:gKCjFJyirr9V-Qkvw6cnLJPPFG2kJc5P@beaver.rmq.cloudamqp.com/ixoayxee
  AWS_REGION: ap-south-1
  MONGO_CONNECTION_STRING: mongodb://scbuser:Prestige@ramkumar-mongodbcluster-shard-00-00.jptuw.mongodb.net:27017,ramkumar-mongodbcluster-shard-00-01.jptuw.mongodb.net:27017,ramkumar-mongodbcluster-shard-00-02.jptuw.mongodb.net:27017/emailrequestsdb?ssl=true&replicaSet=atlas-duot5o-shard-0&authSource=admin&retryWrites=true&w=majority
  EMAIL_REQUESTS_QUEUE: email-requests-queue

---

apiVersion: v1
kind: Secret
metadata:
  name: casestudy-emailservice-secret
  labels:
    env: staging
    businessUnit: emailService
data:
  AWS_ACCESS_KEY: QUtJQVNDRzVUREROVUVHVVU3V0Q=
  AWS_ACCESS_SECRET_KEY: aVltQU1aR0thVllXU0lrMy9RSzdjZjQ0NVhnSXZ5ZkNzckRRQ1ZGbg==

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-emailservice
  labels:
    env: staging
    businessUnit: emailservice
spec:
  replicas: 1
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['emailService']}
  template:
    metadata:
      name: casestudy-emailservice-pod
      labels:
        env: staging
        businessUnit: emailService
    spec:
      containers:
      - name: casestudy-emailservice-container
        image: iomega/casestudy-emailservice
        env:
        - name: CLOUDAMQP_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: CLOUDAMQP_URL
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: casestudy-emailservice-secret
              key: AWS_ACCESS_KEY
        - name: AWS_ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: casestudy-emailservice-secret
              key: AWS_ACCESS_SECRET_KEY   
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: AWS_REGION                 
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: MONGO_CONNECTION_STRING
        - name: EMAIL_REQUESTS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: EMAIL_REQUESTS_QUEUE                  
        volumeMounts:
        - name: foo
          mountPath: /etc/foo
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: casestudy-emailservice-secret       