apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    env: staging
    businessUnit: database
data:
  MONGO_INITDB_ROOT_PASSWORD: UHJlc3RpZ2U=
stringData:
  MONGO_INITDB_ROOT_USERNAME: root

---      

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/mnt/data"
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---   

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    env: staging
    businessUnit: database
spec:
  replicas: 1
  selector:
    matchLabels:
      env: staging
      businessUnit: database
      app: mongodb
  template:
    metadata:
      labels:
        env: staging
        businessUnit: database
        app: mongodb
    spec:
      containers:
      - name: db
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
            name: mongodb-secret
        volumeMounts:
        - name: mongodb-configuration-file
          mountPath: /etc/mongod.conf
          readOnly: true
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-configuration-file
        configMap:
          name: mongodb-config-file    
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim     

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017  